Предлагать перезапускать упавшие тесты
livestreamx/overhave pull request #30
Opened 2023-12-24 19:02 UTC by k-o-pshenichnikova

2024-01-03 15:04 UTC, SophIren commented on overhave/admin/views/feature.py
> +        self.__class__.data_store = data
FeatureView.data_store = data

2024-01-03 15:05 UTC, SophIren commented on tests/unit/synchronizer/test_synchronizer.py
> +        with patch.object(overhave_synchronizer, "_git_initializer"):
https://stackoverflow.com/questions/3024925/create-a-with-block-on-several-context-managers

Чтобы не плодить лесенки :)

2024-01-03 15:07 UTC, SophIren commented on tests/integration/tokenizer/test_client.py
> +# мы очень стараемся исправить
Зачините плиз 😭 это старые тесты, без них точно не вольем :(

2024-01-04 13:03 UTC, k-o-pshenichnikova commented on tests/integration/tokenizer/test_client.py
> +# мы очень стараемся исправить
я вообще в шоке что эти тесты делают тут, я же с другой ветки пушила.. 
крч в новом коммите удалю вообще этот файл, мы так и не зачинили)

2024-01-04 13:30 UTC, Resinchen requested changes

2024-01-04 13:30 UTC, Resinchen commented on overhave/admin/templates/test_run_detail.html
> +        <input type="submit" class="button restart-btn" value="Restart test" name="restart">
Давайте семантические теги использовать - \<button\>
Как выше

2024-01-09 06:40 UTC, Resinchen commented on overhave/admin/views/scenario_test_run.py
> +            return FeatureView._run_test(data=data, rendered=rendered)
Мне не нравится, что мы дергаем приватный метод в другом классе

2024-01-10 06:50 UTC, Resinchen approved these changes, later dismissed

2024-01-10 08:41 UTC, Resinchen commented on overhave/admin/views/scenario_test_run.py
> +        scenario_id = data.get(f"{_SCENARIO_PREFIX}-id")
Ребят, а вы код то запускаете? Здесь в data приходит None

Предлагаю убрать кусок с проверкой сценария, и брать scenario_id через текущий test_run_id из базы

Текущий test_run_id можно получить из  квери параметров
current_test_run_id = get_mdict_item_or_list(flask.request.args, 'id')

2024-01-11 04:56 UTC, Resinchen commented on overhave/admin/views/scenario_test_run.py
> +                session=session, scenario_id=int(current_test_run_id)
`scenario_id=int(current_test_run_id)`
Кажется тут что-то не так, не думаете?

2024-01-11 05:03 UTC, Resinchen commented on overhave/admin/views/scenario_test_run.py
> +_SCENARIO_PREFIX = "scenario-0"
А зачем оно теперь тут?

2024-01-12 05:28 UTC, k-o-pshenichnikova commented on overhave/admin/templates/test_run_detail.html
> +        <input type="submit" class="button restart-btn" value="Restart test" name="restart">
так мы буквально ваш код взяли) 
Ты имеешь в виду input на button поменять или как, не понимаю(

2024-01-12 05:28 UTC, k-o-pshenichnikova commented on overhave/admin/views/scenario_test_run.py
> +        scenario_id = data.get(f"{_SCENARIO_PREFIX}-id")
Запускали, работало..
Щас зачиним

2024-01-12 05:28 UTC, k-o-pshenichnikova commented on overhave/admin/views/scenario_test_run.py
> +                session=session, scenario_id=int(current_test_run_id)
Я не понимаю что не так( 
test_run_id у нас ведь появляется после того как мы scenario объявили, как по нему вытаскивать тогда..

2024-01-12 06:27 UTC, Resinchen commented on overhave/admin/views/scenario_test_run.py
> +                session=session, scenario_id=int(current_test_run_id)
Ответил

2024-01-12 07:58 UTC, Resinchen approved these changes

2024-01-12 13:27 UTC, merged