Emulation button disabled on click
livestreamx/overhave pull request #32
Opened 2023-12-25 19:37 UTC by TDanilV16

Конюшенко & Пичугин & Титаренко

2024-01-04 13:32 UTC, Resinchen requested changes

2024-01-04 13:32 UTC, Resinchen commented on overhave/admin/templates/emulation_run_detail.html
> +                var myButton = document.getElementsByClassName("button edit-btn");
Метод возвращает не элемент, а список элементов. Лучше добавьте id в элемент и тяните по нему

2024-01-04 13:32 UTC, Resinchen commented on tests/unit/publication/gitlab/test_tokenizer_client.py
> +# flake8: noqa
Почему на всем файле отключили?

2024-01-05 12:30 UTC, alexe0110 commented on overhave/entities/settings.py
> +    emulation_base_cmd: str | None = Field(default="echo")
это точно надо ?

2024-01-09 05:21 UTC, artamaney commented on overhave/entities/settings.py
> +    emulation_base_cmd: str | None = Field(default="echo")
да я попросил брат

2024-01-09 05:22 UTC, artamaney commented on overhave/entities/settings.py
> +    emulation_base_cmd: str | None = Field(default="echo")
или оно так не работает? У Заварина с Русских норм все кста получлиось

2024-01-09 11:16 UTC, TDanilV16 commented on tests/unit/publication/gitlab/test_tokenizer_client.py
> +# flake8: noqa
Отключал на конкретной строчке, но при этом другой линтер ругается

2024-01-09 11:21 UTC, TDanilV16 commented on overhave/entities/settings.py
> +    emulation_base_cmd: str | None = Field(default="echo")
Я так и не понял, нужно оно или нет. Жду более подробных инструкций

2024-01-09 15:40 UTC, TDanilV16 commented on overhave/admin/templates/emulation_run_detail.html
> +                var myButton = document.getElementsByClassName("button edit-btn");
Поменял

2024-01-09 20:26 UTC, artamaney commented on overhave/entities/settings.py
> +    emulation_base_cmd: str | None = Field(default="echo")
удали

2024-01-09 20:26 UTC, artamaney commented on tests/unit/publication/gitlab/test_tokenizer_client.py
> +# flake8: noqa
удалите эти тесты они тут не причом, только удлинят ревью ваше
это другая история (задача)

2024-01-10 06:18 UTC, TDanilV16 commented on overhave/entities/settings.py
> +    emulation_base_cmd: str | None = Field(default="echo")
Удалил

2024-01-10 06:18 UTC, TDanilV16 commented on tests/unit/publication/gitlab/test_tokenizer_client.py
> +# flake8: noqa
Удалил

2024-01-10 08:56 UTC, SophIren commented on overhave/admin/templates/emulation_run_detail.html
> +            function disableButton() {
Давайте еще тест сделаем на то, что кнопка исчезает 👹
Это кажется несложно)

2024-01-10 08:57 UTC, SophIren commented on overhave/admin/templates/emulation_run_detail.html
> +            function disableButton() {
А она просто дизейблится

2024-01-11 04:57 UTC, Resinchen commented on overhave/admin/templates/emulation_run_detail.html
> +        <button class="button edit-btn" id="emulationRunBtn" onclick="disableButton()">Edit template</button>
Кнопка про редактирование темплейта, а id-шник называется кнопка  запуска эмуляции

2024-01-11 04:57 UTC, Resinchen commented on tests/unit/publication/gitlab/test_tokenizer_client.py
> +# flake8: noqa
Какие ошибки?

2024-01-11 18:56 UTC, Resinchen approved these changes

2024-01-12 07:38 UTC, merged